config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "chatroom#index"

  get 'signup', to: 'user#new'

  post 'signup', to: 'user#create'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    after_create_commit {broadcast_append_to "chatroom"}
    scope :custom_display, -> { order(:created_at).last(50)}
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 20}
    has_secure_password
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

    before_action :require_user

    def index
        @message = Message.new
        @messages = Message.custom_display
        @users = User.all
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      ActionCable.server.broadcast "chatroom_channel", { 
        message: render_message(@message, current_user) 
      }
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message, current_user)
    ApplicationController.renderer.render(partial: 'messages/message', locals: { message: message, current_user: current_user })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :logged_in_redirect, only: [:new, :create]

    def new
    end

    def create
        @user = User.find_by(username: params[:session][:username])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            flash[:success] = "Logged in successfully"
            redirect_to root_path
        else
            flash.now[:danger] = "There was something wrong with your log in information"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Successfully logged out"
        redirect_to login_path
    end

    
    private
    
    def logged_in_redirect
        if logged_in?
            flash[:danger] = "You are already logged in"
            redirect_to root_path
        end
    end
    
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to login_path
            flash[:success] = "Successfully signed up, please log in"
        else
            render 'new'
            flash.now[:danger] = "Something went wrong"
        end
    end


    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chatroom/index.html.erb
<div class="container">
    <div class="row">
        <div class="card col-sm-3 mt-3 mb-3 mx-auto">
            <div class="card-header text-center d-flex align-items-center justify-content-center">
                <%= image_tag 'favicon.ico' %>
            </div>
            <div class="card-body">
                <p class="fs-3 text-center fw-bold"> Send a Message </p>
            </div>
        </div>
    </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-9">
        <div class="card px-5 pb-5 pt-3" style="height: 450px;">
            <p class="text-center fw-bold"> Messages </p>
            <div class="list-group overflow-scroll" style="overflow-y: scroll;" id="chatbox">
                <!-- Received Message -->
                <%= turbo_stream_from "chatroom" %>
                <div class="text-end" id="messages">
                    <% @messages.each do |message| %>
                        <%= render 'messages/message', message: message %>
                    <% end %>
                </div>
            </div>
            <%= form_for(@message, html: {class: "mt-3", id: "message_form"}, url: message_path, remote: true) do |f| %>
                <div class="row g-2 align-items-center">
                    <div class="col">
                        <%= f.text_field :body, placeholder: "Type a message...", class: "form-control" %>
                    </div>
                    <div class="col-auto">
                        <%= f.submit 'Send', class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
            
        </div>
    </div>
    <div class="col-md-3">
        <div class="card p-3" style="height: 400px;">
            <p class="text-center fw-bold"> Users </p>
            <ul class="list-group overflow-scroll">
                <% @users.each do |user| %>
                    <li class="list-group-item"><%= user.username %></li>
                <% end %>
            </ul>
        </div>
    </div>
  </div>
</div>

<script>
    window.onload = function() {
        var chatbox = document.getElementById('chatbox');
        chatbox.scrollTop = chatbox.scrollHeight;
    };
</script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('message_form').addEventListener('submit', function() {
        setTimeout(function() {
            document.getElementById('message_form').reset();
        }, 0);
        });
    });
</script>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
    <div class="alert alert-<%= message_type %> alert-dismissible fade show mt-3" role="alert">
        <%= message_content %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="navbar-brand" >MessageMe</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Chatroom', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
            </a>
            <ul class="dropdown-menu">
            <% if logged_in? %>
                <li><%= button_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %></li>
            <% else %>
                <li><%= link_to 'Log in', login_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'Sign up', signup_path, class: "dropdown-item" %></li>
            <% end %>
            </ul>
        </li>
    </ul>
    <% if !logged_in? %>
        <%= link_to 'Log In', login_path, class: "btn btn-primary" %>
    <% else %>
        <%= button_to 'Log out', logout_path, method: :delete, class: "btn btn-primary" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload"%>
  </head>

  <body>
    <nav class="navbar bg-dark border-bottom border-body navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
  <div class="list-group-item">
    <div class="d-flex w-100 justify-content-start" style="height: 25px;">
      <strong class="me-2"><%= message.user.username %>:</strong>
      <p><%= message.body %></p>
    </div>
  </div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append 'message-container', partial: 'messages/message', locals: { message: @message } %>

app/views/user/new.html.erb
<h3 class="text-center mt-5 w-4"> Sign up</h3>
<div class="row card">
    <div class="col-md-6 mx-auto">
        <div class="card-body">
            <%= form_for(@user, url: signup_path, html: { class: "text-center", 'data-turbo': 'false' }) do |form| %>
                <div class="mb-3">
                    <%= form.label :username, class: 'form-label fw-bold' %>
                    <%= form.text_field :username, id: 'loginEmail', class: 'form-control', placeholder: 'Enter username' %>
                </div>
                <div class="mb-3">
                    <%= form.label :password, class: 'form-label fw-bold' %>
                    <%= form.password_field :password, id: 'loginPassword', class: 'form-control', placeholder: 'Password' %>
                </div>
                <%= form.button 'Sign Up', class: 'btn btn-primary' %>
            <% end %>
        </div>
    </div>
</div>